version: '3.1'
services:
    healthcli:
        image: ericksaraiva/healthcli
        container_name: healthcli
        networks:
          compose-bridge:


networks: 
    compose-bridge: 
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.20.20.4/16
